package rvr.magenative.easyvalidation;

import java.util.HashMap;

public class CountryList {


    public static final String Afghanistan = "AF";
    public static final String Aland_Islands = "AX";
    public static final String Albania = "AL";
    public static final String Algeria = "DZ";
    public static final String American_Samoa = "AS";
    public static final String Andorra = "AD";
    public static final String Angola = "AO";
    public static final String Anguilla = "AI";
    public static final String Antarctica = "AQ";
    public static final String Antigua_and_Barbuda = "AG";
    public static final String Argentina = "AR";
    public static final String Armenia = "AM";
    public static final String Aruba = "AW";
    public static final String Australia  =  "AU";
    public static final String Austria  =  "AT";
    public static final String Azerbaijan  =  "AZ";
    public static final String Bahamas = "BS";
    public static final String Bahrain = "BH";
    public static final String Bangladesh = "BD";
    public static final String Barbados = "BB";
    public static final String Belarus = "BY";
    public static final String Belgium = "BE";
    public static final String Belize = "BZ";
    public static final String Benin = "BJ";
    public static final String Bermuda = "BM";
    public static final String Bhutan = "BT";
    public static final String Bolivia = "BO";
    public static final String Bosnia_and_Herzegovina = "BA";
    public static final String Botswana = "BW";
    public static final String Bouvet_Island = "BV";
    public static final String Brazil = "BR";
    public static final String British_Indian_Ocean_Territory = "IO";
    public static final String Brunei_Darussalam = "BN";
    public static final String Bulgaria = "BG";
    public static final String Burkina_Faso = "BF";
    public static final String Burundi = "BI";
    public static final String Cambodia = "KH";
    public static final String Cameroon = "CM";
    public static final String Canada = "CA";
    public static final String Cape_Verde = "CV";
    public static final String Cayman_Islands = "KY";
    public static final String Central_African_Republic = "CF";
    public static final String Chad = "TD";
    public static final String Chile = "CL";
    public static final String China = "CN";
    public static final String Christmas_Island = "CX";
    public static final String Cocos_Keeling_Islands = "CC";
    public static final String Colombia = "CO";
    public static final String Comoros = "KM";
    public static final String Congo = "CG";
    public static final String Congo_The_Democratic_Republic_of_the = "CD";
    public static final String Cook_Islands = "CK";
    public static final String Costa_Rica = "CR";
    public static final String Cote_DIvoire = "CI";
    public static final String Croatia = "HR";
    public static final String Cuba = "CU";
    public static final String Cyprus = "CY";
    public static final String Czech_Republic = "CZ";
    public static final String Denmark = "DK";
    public static final String Djibouti = "DJ";
    public static final String Dominica = "DM";
    public static final String Dominican_Republic = "DO";
    public static final String Ecuador = "EC";
    public static final String Egypt = "EG";
    public static final String El_Salvador = "SV";
    public static final String Equatorial_Guinea = "GQ";
    public static final String Eritrea = "ER";
    public static final String Estonia = "EE";
    public static final String Ethiopia = "ET";
    public static final String Falkland_Islands_Malvinas = "FK";
    public static final String Faroe_Islands = "FO";
    public static final String Fiji = "FJ";
    public static final String Finland = "FI";
    public static final String France = "FR";
    public static final String French_Guiana = "GF";
    public static final String French_Polynesia = "PF";
    public static final String French_Southern_Territories = "TF";
    public static final String Gabon = "GA";
    public static final String Gambia = "GM";
    public static final String Georgia = "GE";
    public static final String Germany = "DE";
    public static final String Ghana = "GH";
    public static final String Gibraltar = "GI";
    public static final String Greece = "GR";
    public static final String Greenland = "GL";
    public static final String Grenada = "GD";
    public static final String Guadeloupe = "GP";
    public static final String Guam = "GU";
    public static final String Guatemala = "GT";
    public static final String Guernsey = "GG";
    public static final String Guinea = "GN";
    public static final String Guinea_Bissau = "GW";
    public static final String Guyana = "GY";
    public static final String Haiti = "HT";
    public static final String Heard_Island_and_Mcdonald_Islands = "HM";
    public static final String Holy_See_Vatican_City_State = "VA";
    public static final String Honduras = "HN";
    public static final String Hong_Kong = "HK";
    public static final String Hungary = "HU";
    public static final String Iceland = "IS";
    public static final String India = "IN";
    public static final String Indonesia = "ID";
    public static final String Iran_Islamic_Republic_Of_Iran = "IR";
    public static final String Iraq = "IQ";
    public static final String Ireland = "IE";
    public static final String Isle_of_Man = "IM";
    public static final String Israel = "IL";
    public static final String Italy = "IT";
    public static final String Jamaica = "JM";
    public static final String Japan = "JP";
    public static final String Jersey = "JE";
    public static final String Jordan = "JO";
    public static final String Kazakhstan = "KZ";
    public static final String Kenya = "KE";
    public static final String Kiribati = "KI";
    public static final String Korea_Democratic_People_Republic_of = "KP";
    public static final String Korea_Republic_of = "KR";
    public static final String Kuwait = "KW";
    public static final String Kyrgyzstan = "KG";
    public static final String Lao_People_Democratic_Republic = "LA";
    public static final String Latvia = "LV";
    public static final String Lebanon = "LB";
    public static final String Lesotho = "LS";
    public static final String Liberia = "LR";
    public static final String Libyan_Arab_Jamahiriya = "LY";
    public static final String Liechtenstein = "LI";
    public static final String Lithuania = "LT";
    public static final String Luxembourg = "LU";
    public static final String Macao = "MO";
    public static final String Macedonia_The_Former_Yugoslav_Republic_of = "MK";
    public static final String Madagascar = "MG";
    public static final String Malawi = "MW";
    public static final String Malaysia = "MY";
    public static final String Maldives = "MV";
    public static final String Mali = "ML";
    public static final String Malta = "MT";
    public static final String Marshall_Islands = "MH";
    public static final String Martinique = "MQ";
    public static final String Mauritania = "MR";
    public static final String Mauritius = "MU";
    public static final String Mayotte = "YT";
    public static final String Mexico = "MX";
    public static final String Micronesia_Federated_States_of = "FM";
    public static final String Moldova_Republic_of = "MD";
    public static final String Monaco = "MC";
    public static final String Mongolia = "MN";
    public static final String Montserrat = "MS";
    public static final String Morocco = "MA";
    public static final String Mozambique = "MZ";
    public static final String Myanmar = "MM";
    public static final String Namibia = "NA";
    public static final String Nauru = "NR";
    public static final String Nepal = "NP";
    public static final String Netherlands = "NL";
    public static final String Netherlands_Antilles = "AN";
    public static final String New_Caledonia = "NC";
    public static final String New_Zealand = "NZ";
    public static final String Nicaragua = "NI";
    public static final String Niger = "NE";
    public static final String Nigeria = "NG";
    public static final String Niue = "NU";
    public static final String Norfolk_Island = "NF";
    public static final String Northern_Mariana_Islands = "MP";
    public static final String Norway = "NO";
    public static final String Oman = "OM";
    public static final String Pakistan = "PK";
    public static final String Palau = "PW";
    public static final String Palestinian_Territory_Occupied = "PS";
    public static final String Panama = "PA";
    public static final String Papua_New_Guinea = "PG";
    public static final String Paraguay = "PY";
    public static final String Peru = "PE";
    public static final String Philippines = "PH";
    public static final String Pitcairn = "PN";
    public static final String Poland = "PL";
    public static final String Portugal = "PT";
    public static final String Puerto_Rico = "PR";
    public static final String Qatar = "QA";
    public static final String Reunion = "RE";
    public static final String Romania = "RO";
    public static final String Russian_Federation = "RU";
    public static final String RWANDA = "RW";
    public static final String Saint_Helena = "SH";
    public static final String Saint_Kitts_and_Nevis = "KN";
    public static final String Saint_Lucia = "LC";
    public static final String Saint_Pierre_and_Miquelon = "PM";
    public static final String Saint_Vincent_and_the_Grenadines = "VC";
    public static final String Samoa = "WS";
    public static final String San_Marino = "SM";
    public static final String Sao_Tome_and_Principe = "ST";
    public static final String Saudi_Arabia = "SA";
    public static final String Senegal = "SN";
    public static final String Serbia_and_Montenegro = "CS";
    public static final String Seychelles = "SC";
    public static final String Sierra_Leone = "SL";
    public static final String Singapore = "SG";
    public static final String Slovakia = "SK";
    public static final String Slovenia = "SI";
    public static final String Solomon_Islands = "SB";
    public static final String Somalia = "SO";
    public static final String South_Africa = "ZA";
    public static final String South_Georgia_and_the_South_Sandwich_Islands = "GS";
    public static final String Spain = "ES";
    public static final String Sri_Lanka = "LK";
    public static final String Sudan = "SD";
    public static final String Suriname = "SR";
    public static final String Svalbard_and_Jan_Mayen = "SJ";
    public static final String Swaziland = "SZ";
    public static final String Sweden = "SE";
    public static final String Switzerland = "CH";
    public static final String Syrian_Arab_Republic = "SY";
    public static final String Taiwan_Province_of_China = "TW";
    public static final String Tajikistan = "TJ";
    public static final String Tanzania_United_Republic_of = "TZ";
    public static final String Thailand = "TH";
    public static final String Timor_Leste = "TL";
    public static final String Togo = "TG";
    public static final String Tokelau = "TK";
    public static final String Tonga = "TO";
    public static final String Trinidad_and_Tobago = "TT";
    public static final String Tunisia = "TN";
    public static final String Turkey = "TR";
    public static final String Turkmenistan = "TM";
    public static final String Turks_and_Caicos_Islands = "TC";
    public static final String Tuvalu = "TV";
    public static final String Uganda = "UG";
    public static final String Ukraine = "UA";
    public static final String United_Arab_Emirates = "AE";
    public static final String United_Kingdom = "GB";
    public static final String United_States = "US";
    public static final String United_States_Minor_Outlying_Islands = "UM";
    public static final String Uruguay = "UY";
    public static final String Uzbekistan = "UZ";
    public static final String Vanuatu = "VU";
    public static final String Venezuela = "VE";
    public static final String Viet_Nam = "VN";
    public static final String Virgin_Islands_British = "VG";
    public static final String Virgin_Islands_U_S = "VI";
    public static final String Wallis_and_Futuna = "WF";
    public static final String Western_Sahara = "EH";
    public static final String Yemen = "YE";
    public static final String Zambia = "ZM";
    public static final String Zimbabwe = "ZW";
    


    public static String getCountryPhone(String countryCode){
        return countryPhoneCodeList().get(countryCode);
    }



    private static HashMap<String, String> countryPhoneCodeList(){

        HashMap<String,String> countryPhoneCodeMap =new HashMap<String, String>();
        countryPhoneCodeMap.put("US","+1");
        countryPhoneCodeMap.put("AG","+1");
        countryPhoneCodeMap.put("AI","+1");
        countryPhoneCodeMap.put("AS","+1");
        countryPhoneCodeMap.put("BB","+1");
        countryPhoneCodeMap.put("BM","+1");
        countryPhoneCodeMap.put("BS","+1");
        countryPhoneCodeMap.put("CA","+1");
        countryPhoneCodeMap.put("DM","+1");
        countryPhoneCodeMap.put("DO","+1");
        countryPhoneCodeMap.put("GD","+1");
        countryPhoneCodeMap.put("GU","+1");
        countryPhoneCodeMap.put("JM","+1");
        countryPhoneCodeMap.put("KN","+1");
        countryPhoneCodeMap.put("KY","+1");
        countryPhoneCodeMap.put("LC","+1");
        countryPhoneCodeMap.put("MP","+1");
        countryPhoneCodeMap.put("MS","+1");
        countryPhoneCodeMap.put("PR","+1");
        countryPhoneCodeMap.put("SX","+1");
        countryPhoneCodeMap.put("TC","+1");
        countryPhoneCodeMap.put("TT","+1");
        countryPhoneCodeMap.put("VC","+1");
        countryPhoneCodeMap.put("VG","+1");
        countryPhoneCodeMap.put("VI","+1");
        countryPhoneCodeMap.put("RU","+7");
        countryPhoneCodeMap.put("KZ","+7");
        countryPhoneCodeMap.put("EG","+28");
        countryPhoneCodeMap.put("ZA","+27");
        countryPhoneCodeMap.put("GR","+30");
        countryPhoneCodeMap.put("NL","+31");
        countryPhoneCodeMap.put("BE","+32");
        countryPhoneCodeMap.put("FR","+33");
        countryPhoneCodeMap.put("ES","+34");
        countryPhoneCodeMap.put("HU","+36");
        countryPhoneCodeMap.put("IT","+39");
        countryPhoneCodeMap.put("VA","+39");
        countryPhoneCodeMap.put("RO","+40");
        countryPhoneCodeMap.put("CH","+41");
        countryPhoneCodeMap.put("AT","+43");
        countryPhoneCodeMap.put("GB","+44");
        countryPhoneCodeMap.put("GG","+44");
        countryPhoneCodeMap.put("IM","+44");
        countryPhoneCodeMap.put("JE","+44");
        countryPhoneCodeMap.put("DK","+45");
        countryPhoneCodeMap.put("SE","+46");
        countryPhoneCodeMap.put("NO","+47");
        countryPhoneCodeMap.put("SJ","+47");
        countryPhoneCodeMap.put("PL","+48");
        countryPhoneCodeMap.put("DE","+49");
        countryPhoneCodeMap.put("PE","+51");
        countryPhoneCodeMap.put("MX","+52");
        countryPhoneCodeMap.put("CU","+53");
        countryPhoneCodeMap.put("AR","+54");
        countryPhoneCodeMap.put("BR","+55");
        countryPhoneCodeMap.put("CL","+56");
        countryPhoneCodeMap.put("CO","+57");
        countryPhoneCodeMap.put("VE","+58");
        countryPhoneCodeMap.put("MY","+60");
        countryPhoneCodeMap.put("AU","+61");
        countryPhoneCodeMap.put("CC","+61");
        countryPhoneCodeMap.put("CX","+61");
        countryPhoneCodeMap.put("ID","+62");
        countryPhoneCodeMap.put("PH","+63");
        countryPhoneCodeMap.put("NZ","+64");
        countryPhoneCodeMap.put("SG","+65");
        countryPhoneCodeMap.put("TH","+66");
        countryPhoneCodeMap.put("JP","+81");
        countryPhoneCodeMap.put("KR","+82");
        countryPhoneCodeMap.put("VN","+84");
        countryPhoneCodeMap.put("CN","+86");
        countryPhoneCodeMap.put("TR","+90");
        countryPhoneCodeMap.put("IN","+91");
        countryPhoneCodeMap.put("PK","+92");
        countryPhoneCodeMap.put("AF","+93");
        countryPhoneCodeMap.put("LK","+94");
        countryPhoneCodeMap.put("MM","+95");
        countryPhoneCodeMap.put("IR","+98");
        countryPhoneCodeMap.put("SS","+211");
        countryPhoneCodeMap.put("MA","+212");
        countryPhoneCodeMap.put("EH","+212");
        countryPhoneCodeMap.put("DZ","+213");
        countryPhoneCodeMap.put("TN","216");
        countryPhoneCodeMap.put("LY","+218");
        countryPhoneCodeMap.put("GM","+228");
        countryPhoneCodeMap.put("SN","+221");
        countryPhoneCodeMap.put("MR","+222");
        countryPhoneCodeMap.put("ML","+223");
        countryPhoneCodeMap.put("GN","+224");
        countryPhoneCodeMap.put("CI","+225");
        countryPhoneCodeMap.put("BF","+226");
        countryPhoneCodeMap.put("NE","+227");
        countryPhoneCodeMap.put("TG","+228");
        countryPhoneCodeMap.put("BJ","+229");
        countryPhoneCodeMap.put("MU","+230");
        countryPhoneCodeMap.put("LR","+231");
        countryPhoneCodeMap.put("SL","+232");
        countryPhoneCodeMap.put("GH","+233");
        countryPhoneCodeMap.put("NG","+234");
        countryPhoneCodeMap.put("TD","+235");
        countryPhoneCodeMap.put("CF","+236");
        countryPhoneCodeMap.put("CM","+237");
        countryPhoneCodeMap.put("CV","+238");
        countryPhoneCodeMap.put("ST","+239");
        countryPhoneCodeMap.put("GQ","+240");
        countryPhoneCodeMap.put("GA","+241");
        countryPhoneCodeMap.put("CG","+242");
        countryPhoneCodeMap.put("CD","+243");
        countryPhoneCodeMap.put("AO","+244");
        countryPhoneCodeMap.put("GW","+245");
        countryPhoneCodeMap.put("IO","+246");
        countryPhoneCodeMap.put("SD","+249");
        countryPhoneCodeMap.put("RW","+250");
        countryPhoneCodeMap.put("ET","+251");
        countryPhoneCodeMap.put("SO","+252");
        countryPhoneCodeMap.put("DJ","+253");
        countryPhoneCodeMap.put("KE","+254");
        countryPhoneCodeMap.put("TZ","+255");
        countryPhoneCodeMap.put("UG","+256");
        countryPhoneCodeMap.put("BI","+257");
        countryPhoneCodeMap.put("MZ","+258");
        countryPhoneCodeMap.put("ZM","+260");
        countryPhoneCodeMap.put("MG","+261");
        countryPhoneCodeMap.put("RE","+262");
        countryPhoneCodeMap.put("YT","+262");
        countryPhoneCodeMap.put("ZW","+263");
        countryPhoneCodeMap.put("NA","+264");
        countryPhoneCodeMap.put("MW","+265");
        countryPhoneCodeMap.put("LS","+266");
        countryPhoneCodeMap.put("BW","+267");
        countryPhoneCodeMap.put("SZ","+265");
        countryPhoneCodeMap.put("KM","+269");
        countryPhoneCodeMap.put("SH","+290");
        countryPhoneCodeMap.put("ER","+291");
        countryPhoneCodeMap.put("AW","+297");
        countryPhoneCodeMap.put("FO","+298");
        countryPhoneCodeMap.put("GL","+299");
        countryPhoneCodeMap.put("GI","+350");
        countryPhoneCodeMap.put("PT","+351");
        countryPhoneCodeMap.put("LU","+352");
        countryPhoneCodeMap.put("IE","+353");
        countryPhoneCodeMap.put("IS","+354");
        countryPhoneCodeMap.put("AL","+355");
        countryPhoneCodeMap.put("MT","+356");
        countryPhoneCodeMap.put("CY","+357");
        countryPhoneCodeMap.put("FI","+358");
        countryPhoneCodeMap.put("AX","+358");
        countryPhoneCodeMap.put("BG","+359");
        countryPhoneCodeMap.put("LT","+370");
        countryPhoneCodeMap.put("LV","+371");
        countryPhoneCodeMap.put("EE","+372");
        countryPhoneCodeMap.put("MD","+373");
        countryPhoneCodeMap.put("AM","+374");
        countryPhoneCodeMap.put("BY","+375");
        countryPhoneCodeMap.put("AD","+376");
        countryPhoneCodeMap.put("MC","+377");
        countryPhoneCodeMap.put("SM","+378");
        countryPhoneCodeMap.put("UA","+380");
        countryPhoneCodeMap.put("HR","+385");
        countryPhoneCodeMap.put("SI","+386");
        countryPhoneCodeMap.put("BA","+387");
        countryPhoneCodeMap.put("MK","+389");
        countryPhoneCodeMap.put("CZ","+420");
        countryPhoneCodeMap.put("SK","+421");
        countryPhoneCodeMap.put("LI","+422");
        countryPhoneCodeMap.put("FK","+500");
        countryPhoneCodeMap.put("BZ","+501");
        countryPhoneCodeMap.put("GT","+502");
        countryPhoneCodeMap.put("SV","+503");
        countryPhoneCodeMap.put("HN","+504");
        countryPhoneCodeMap.put("NI","+505");
        countryPhoneCodeMap.put("CR","+506");
        countryPhoneCodeMap.put("PA","+507");
        countryPhoneCodeMap.put("PM","+508");
        countryPhoneCodeMap.put("HT","+509");
        countryPhoneCodeMap.put("GP","+590");
        countryPhoneCodeMap.put("BO","+591");
        countryPhoneCodeMap.put("GY","+592");
        countryPhoneCodeMap.put("EC","+593");
        countryPhoneCodeMap.put("GF","+594");
        countryPhoneCodeMap.put("PY","+595");
        countryPhoneCodeMap.put("MQ","+596");
        countryPhoneCodeMap.put("SR","+597");
        countryPhoneCodeMap.put("UY","+598");
        countryPhoneCodeMap.put("TL","+670");
        countryPhoneCodeMap.put("NF","+672");
        countryPhoneCodeMap.put("BN","+673");
        countryPhoneCodeMap.put("NR","+674");
        countryPhoneCodeMap.put("PG","+675");
        countryPhoneCodeMap.put("TO","+676");
        countryPhoneCodeMap.put("SB","+677");
        countryPhoneCodeMap.put("VU","+678");
        countryPhoneCodeMap.put("FJ","+679");
        countryPhoneCodeMap.put("PW","+680");
        countryPhoneCodeMap.put("WF","+681");
        countryPhoneCodeMap.put("CK","+682");
        countryPhoneCodeMap.put("NU","+683");
        countryPhoneCodeMap.put("WS","+685");
        countryPhoneCodeMap.put("KI","+686");
        countryPhoneCodeMap.put("NC","+687");
        countryPhoneCodeMap.put("TV","+688");
        countryPhoneCodeMap.put("PF","+689");
        countryPhoneCodeMap.put("TK","+690");
        countryPhoneCodeMap.put("FM","+691");
        countryPhoneCodeMap.put("MH","+692");
        countryPhoneCodeMap.put("KP","+850");
        countryPhoneCodeMap.put("HK","+852");
        countryPhoneCodeMap.put("MO","+853");
        countryPhoneCodeMap.put("KH","+855");
        countryPhoneCodeMap.put("LA","+856");
        countryPhoneCodeMap.put("BD","+880");
        countryPhoneCodeMap.put("TW","+886");
        countryPhoneCodeMap.put("MV","+960");
        countryPhoneCodeMap.put("LB","+961");
        countryPhoneCodeMap.put("JO","+962");
        countryPhoneCodeMap.put("SY","+963");
        countryPhoneCodeMap.put("IQ","+964");
        countryPhoneCodeMap.put("KW","+965");
        countryPhoneCodeMap.put("SA","+966");
        countryPhoneCodeMap.put("YE","+967");
        countryPhoneCodeMap.put("OM","+968");
        countryPhoneCodeMap.put("PS","+970");
        countryPhoneCodeMap.put("AE","+971");
        countryPhoneCodeMap.put("IL","+972");
        countryPhoneCodeMap.put("BH","+973");
        countryPhoneCodeMap.put("QA","+974");
        countryPhoneCodeMap.put("BT","+975");
        countryPhoneCodeMap.put("MN","+976");
        countryPhoneCodeMap.put("NP","+977");
        countryPhoneCodeMap.put("TJ","+992");
        countryPhoneCodeMap.put("TM","+993");
        countryPhoneCodeMap.put("AZ","+994");
        countryPhoneCodeMap.put("GE","+995");
        countryPhoneCodeMap.put("KG","+996");
        countryPhoneCodeMap.put("UZ","+998");

        return countryPhoneCodeMap;
        
    }
    

}
